name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build PWA
      run: npm run build

    - name: Verify build output
      run: |
        ls -la dist/
        echo "Build completed successfully"

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: '34.0.0'
        cmake: '3.22.1'
        ndk: '25.2.9519653'

    - name: Set Android SDK environment
      run: |
        echo "ANDROID_HOME=${ANDROID_HOME}" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}" >> $GITHUB_ENV

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Install Capacitor Android
      run: npm install @capacitor/android

    - name: Copy web assets
      run: npx cap copy android

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set Gradle permissions
      run: chmod +x android/gradlew

    - name: Build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace --info

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk